### ISSUE TITLE
Outdated libp2p-interface

### ISSUE THREAD

**Issue by ajaleksa** [ipfs/helia#119]
Currently, helia uses "@libp2p/interface-libp2p": "^1.1.0", but the actual version in [this](https://github.com/libp2p/js-libp2p-interfaces/blob/master/packages/interface-libp2p/package.json) repo is "version": "3.1.0". I am using typescript and I'm getting a lot of errors. One example, to be more specific is with using pubsub. On version 3.1.0, libp2p uses pubsub on services property (i.e. libp2p.services.pubsub), where older version uses pubsub in root of an object (i.e. libp2p.pubsub). This produces linting errors, but maybe it could be fixed easily, not sure..? There are probably a lot more incompatibilities, but the one I also noticed is while passing libp2p in options of createHelia function.

Cheers

**Comment by achingbrain** [comment]
This will be fixed by upgrading to `libp2p@0.45.x`, likely later this week - it'll be done as part of this PR: https://github.com/ipfs/helia/pull/118

Please stick with `libp2p@0.44.x` for now - of note gossipsub won't work with `0.45.x` until https://github.com/ChainSafe/js-libp2p-gossipsub/pull/428 is merged.

**Comment by achingbrain** [comment]
Fixed in `helia@1.1.0` - please update when you are ready.
