### ISSUE TITLE
more about use of whatwg/fs

### ISSUE THREAD

**Issue by jimmywarting** [ipfs/helia#123]
Currently the web uses indexeddb
but there is a new kid on the web called [whatwg/fs](https://github.com/whatwg/fs) and also the use of [file system access](https://github.com/WICG/file-system-access)

i would love to be able to create a mutable file system and just simple create a ipfs node and share it's identifier and load it as just `<cid>/path/src/index.html` or something

having file system access also means that the file can be changed or added dynamically without js even knowing anything about it.
so it would be cool to have some kind of sort of dynamic support for this.

i don't want to have to put all my files in indexeddb to duplicate all the data being stored.

i want to see code examples, docs, best practices for how to best use ipfs with whatwg/fs, (opfs) & file system access.

**Comment by achingbrain** [comment]
The "filesystem" in IPFS is really an abstraction over a bunch of blocks that live in a blockstore.  Even the ["fs" blockstore](https://www.npmjs.com/package/blockstore-fs) is still a blockstore, it just stores them on the filesystem - 

It sounds like you could write a blockstore using the browser filesystem access primitives, that would negate the need to use idb for blocks?

> i don't want to have to put all my files in indexeddb to duplicate all the data being stored.

Kubo has the idea of a "filestore", where it doesn't copy the file into the blockstore, instead works out what the chunks would be and stores a map of them instead, then when they are requested from the network, reads just the requested chunk of the file.

This sounds nice in theory but in practice if some other process or user modifies the files in the filestore - deletes one or changes the content, everything stops working.

> having file system access also means that the file can be changed or added dynamically without js even knowing anything about it

This seems like a worst-case scenario - if a node claims to the network to be the provider of the blocks that make up a file, but it later finds those blocks to have been deleted or modified, the network suffers as people won't be able to resolve content.

> i would love to be able to create a mutable file system and just simple create a ipfs node and share it's identifier and load it as just <cid>/path/src/index.html or something

This sounds like the kind of thing the filestore would let you do, but again what happens if someone deletes or changes the content of `index.html` - the root CID no longer identifies the content?

**Comment by jimmywarting** [comment]
My idea was to create a uniq identifier and then resolve the subpath based on the address. 
I have read some turtorial about some "mutable file system" with ipfs.

**Comment by achingbrain** [comment]
A directory in IPFS can be thought of as a big [UnixFS](https://github.com/ipfs/specs/blob/main/UNIXFS.md) [DAG](https://docs.ipfs.tech/concepts/merkle-dag/).

A CID is derived from the hash of all the blocks that make up the DAG.

If you change the DAG (e.g. add/remove blocks), you need to calculate a new CID otherwise people cannot get the updated set of blocks.

That is, if you create `<cid>/path/src/index.html` then add `my-image.png` to `src`, `<cid>` is no longer valid - anyone requesting it will not see `my-image.png` in the folder.

Instead you'd need to recalculate `<cid>` to `<cid2>` and distribute it somehow.

Likely you'd use [IPNS](https://docs.ipfs.io/concepts/ipns/) for this so instead of `<cid>/path/src/index.html` you'd have `<ipns-name>/path/src/index.html`, but `/path/src/index.html` would still be a [UnixFS](https://github.com/ipfs/specs/blob/main/UNIXFS.md) [DAG](https://docs.ipfs.tech/concepts/merkle-dag/) behind the scenes and not flat files on your hard drive.

You could write an app that made it a set of flat files, answered requests for subpaths, watched the filesystem and kept everything in sync but I think that's outside the scope of this project, though it's certainly something you could build on top of this project.

**Comment by jimmywarting** [comment]
☝️ that is something i would like to try and build and i have attempted it before. but that was like a year ago.

**Comment by achingbrain** [comment]
That's completely understandable!

I'm going to close this issue because this isn't a feature that will be added here but please do post a link to the repo of your app when you are ready to share it.
