### ISSUE TITLE
Unhandled errors when using Helia in browser

### ISSUE THREAD

**Issue by eyalron33** [ipfs/helia#151]
I'm getting console errors when using Helia in the browser. The errors come from bad calls, either to `cid.contact` or to sockets of bootstrap nodes. I get those errors even when trying the [helia-script-tag](https://github.com/ipfs-examples/helia-examples/tree/main/examples/helia-script-tag) or [helia-vite](https://github.com/ipfs-examples/helia-examples/tree/main/examples/helia-vite) examples.

I don't manage to catch and handle these errors. I tried surrounding the `createHelia` with `try..catch`, but it didn't catch those errors.

I get errors both when running in Firefox and Brave, though the errors are slightly different in each. I attached screenshots of that below. The errors are generated when using the apps in `http://localhost:<somePort>/`.

**Questions:**
1. How is it possible to catch and handle such errors?
2. Is it possible to avoid them? Especially the errors in connecting to bootstrap nodes? I'm slightly surprised by these, since I imagined the list of bootstrap nodes to be more robust (thought maybe the connectivity problems are the fault of my settings?).

**Screenshots:**
Firefox console errors:
![firefox](https://github.com/ipfs/helia/assets/20537195/9674a6a1-a9a5-40b2-8302-64d313d3826b)

Brave console errors:
![brave](https://github.com/ipfs/helia/assets/20537195/d88bdbc2-6112-41e0-9fbe-5ae099167dd0)

**Comment by eyalron33** [comment]
It still persists today. I think that maybe what @whizzzkid proposed, that my network blocks `wss` connections (when using `localhost`) is the cause.

I'll try to play later with the libp2p configuration and see if I can improve it. If yes I'll report here. Anyway, it doesn't do any harm, it's just my OCD of trying to handle all error messages in the console :-)

**Comment by sim31** [comment]
I getting the same errors, when trying to run [helia vite example](https://github.com/ipfs-examples/helia-examples/tree/main/examples/helia-vite).

I'm not sure if the errors are as harmless as @eyalron33 says. While the example app seems to be working, I expected that content added through this app would be discoverable by other ipfs nodes. But I'm not able to retrieve it through my local kubo node.

Is it a bug, which might be related to the errors above or am I misunderstanding what the example app should be doing?

**Comment by SgtPooki** [comment]
@eyalron33 @sim31 

> These sorts of errors are logged by the browser and they're not catchable 😭

This is still true and not something we can control. We have to *attempt* to dial peers to know if we can connect to them. If we don't attempt the dials, we can't connect to peers. Not all attempts are expected to be successful. The failed attempts will show as errors in the console.

I just posted an example of fetching content from a helia node to https://discuss.ipfs.tech/t/how-to-retrieve-content-uploaded-via-helia-using-the-ipfs-gateway/16582/6?u=sgtpooki that you can check out to see that things do work. 

You can use the [helia-connectivity-demo](https://codesandbox.io/p/sandbox/helia-script-tag-forked-3q8y35) to see the status of a browser Helia node. If you're not seeing connected peers, then no networking activities will work. If you are seeing connected peers, you will *still* see these errors in the browser because we cannot control them.

If you want to hide these errors because they're detracting from your users experience in your app, then you may want to run helia in a web-worker/service-worker which should hide the errors from the main console.

I'm going to close this issue because these errors are a normal part of failed attempts to connect to a large variety of nodes throughout the IPFS p2p network.
