### ISSUE TITLE
PeerId changes every time there's a refresh in the site

### ISSUE THREAD

**Issue by logesh2496** [ipfs/helia#155]
In the js-ipfs package when we refresh the site the peerId of the node stays the same. Even if we try to instantiate an instance again there's an error ".ipfs/repo.lock".

How do I configure the node to keep one "PeerId" for a user/browser instance?

Thanks

**Comment by tabcat** [comment]
This is likely due to the [datastore](https://github.com/ipfs/js-stores/tree/main/packages/interface-datastore) option not being provided in the createHelia options. By default this is a MemoryDatastore which is not persisted. You will also want to provide a persisted [blockstore](https://github.com/ipfs/js-stores/tree/main/packages/interface-blockstore) in the options to persist the ipfs repo data.

**Comment by tabcat** [comment]
The repos I linked should list implementations in the READMEs

**Comment by SgtPooki** [comment]
@logesh2496 You can use the `datastore-level` package to have a persistent datastore, which will persist your PeerId.

An example of this is at https://codesandbox.io/p/sandbox/helia-script-tag-forked-3q8y35?file=%2Fsrc%2Findex.js%3A103%2C1-104%2C1. You can refresh the page as many times as you want and the PeerId is the same as the last (as long as you don't clear the datastore)
