### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED: No "exports" main defined in helia/package.json

### ISSUE THREAD

**Issue by charlesxsh** [ipfs/helia#190]
Error
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /<path>/node_modules/helia/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1033:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/sxia/code/dasset/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

main.ts
```
import { strings } from '@helia/strings';
import { createHelia } from 'helia';

(async () =>{
    const helia = await createHelia();
})()
```

dependencies:
"helia": "^1.3.8"

"@helia/strings": "^1.0.0",

When I just simply run the above code with `ts-node main.ts`

**Comment by tomachianura** [comment]
+1
this is very bad, and needs to be addressed as soon as possible.

**Comment by hebr3rt** [comment]
I'm having same issue

**Comment by achingbrain** [comment]
Helia is an ESM-only module.  You cannot use `require` to load it, you must use `import`.

If you cannot use ESM for your project, you can use the [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) function to import it - please see the [helia-cjs example](https://github.com/ipfs-examples/helia-cjs) for more.

**Comment by tomachianura** [comment]
I’m using import, on a nestjs project.
And obviously it doesn’t work, still same error described in this thread.

**Comment by SgtPooki** [comment]
@tomachianura can you provide your source code or a reproducible example so we can dive deeper?

**Comment by SgtPooki** [comment]
For others here, please check out https://github.com/ipfs/helia/issues/216#issuecomment-1669558901 and let us know if you continue to have issues, but confirm your build tool supports ESM.

**Comment by achingbrain** [comment]
There's also [helia-ts-node example](https://github.com/ipfs-examples/helia-ts-node) to show how to get it working, it needs a bit of extra config.

**Comment by tomachianura** [comment]
we work with CommonJS, and we can't change this.
Helia shall fully support CommonJS as well, right?

**Comment by achingbrain** [comment]
Yes, please see the [helia-cjs example](https://github.com/ipfs-examples/helia-cjs) for how to use Helia from a CommonJS project.

**Comment by tomachianura** [comment]
even when looking at 
https://github.com/ipfs-examples/helia-cjs
just doesn't work on an existing nestJS project using CommonJS.

can you kindly provide any solution to that please?
thanks in advance for your support and for being so reactive on this topic.

**Comment by achingbrain** [comment]
> just doesn't work on an existing nestJS project using CommonJS.

I'm guessing that you have a NextJS project, you've set `"module"` to `"CommonJS"`.

I'm guessing that you've done something like:

```ts
const { createHelia } = await import('helia');
```

and you've checked your output folder and seen it being transpiled to:

```js
const { createHelia } = await Promise.resolve().then(() => require('helia'));
```

The [solution](https://github.com/microsoft/TypeScript/issues/43329#issuecomment-1478554107) here appears to be to change `"moduleResolution"` to `"Node16"` - this prevents the dynamic `import` from being transpiled to `require`.

If this does not solve your problem then you are going to have to provide a link to your source code or a reproducible example for us to assist further, because all this guess work has a high cost in time spent and a low probability of success.

**Comment by tomachianura** [comment]
it's not Next, it's Nest :)
changing moduleResolution to Node16 breaks the entire project as well.
our engine is totally closed source, but it's enough to start a new nestjs app (which by default is CommonJS) and install helia to make it crash with the ERR_PACKAGE_PATH_NOT_EXPORTED error.

Clearly, your suggestions described in the helia-nestjs doesn't work, cause changing CommonJS for something else is NOT a solution, considering it'll break a whole project.

Looking forward to have a valid solution, thanks again!
PS: let me know if you need a clean nestjs app with helia installed and crashing, i can create it in the next days once back home.

wish you all a great weekend ahead!

**Comment by SgtPooki** [comment]
> PS: let me know if you need a clean nestjs app with helia installed and crashing, i can create it in the next days once back home.



Yes please. We can provide much better help with reproducible code. Thanks!

**Comment by achingbrain** [comment]
TBH I'm not sure if that's going to add much value since there an [example available](https://github.com/ipfs-examples/helia-nestjs) of how to configure NestJS to work with Helia, so we know the default settings for NestJS are to build CJS, and we know the config changes needed to make it build ESM, but you can't apply them because it "breaks the entire project".

The root of the issue here is that `ERR_PACKAGE_PATH_NOT_EXPORTED` is caused when CJS code uses `require` to load an ES module.

To prevent his happening you have to `import` it, or `await import` if you have to stick on CJS.

Your TypeScript settings are (I think, please confirm) transpiling `await import('helia')` to `await Promise.resolve().then(() => require('helia')` which just isn't going to work.

This is not a problem specific to Helia, you'll have this problem with any module written in ESM that use an exports map.

I suggest fixing your project so it can work with ES modules.

If you won't do this then the only other thing you can do is try to defeat the transpilation of `import` to `require` by using eval:

```js
const { createHelia } = await eval('import("helia")')
```

**Comment by sosioo** [comment]
'Helia is an ESM-only module. You cannot use require to load it, you must use import."
This is absolutely insane. Probably a deal breaker for many developers. You might think the people behind Helia would care about adoption and give the community a product easy to use but obviously that's not the case. 
IPFS was a good it for my Electron app project but unfortunately I cannot use it. That's just sad.

**Comment by achingbrain** [comment]
There is nothing stopping you from using Helia in Electron - please see the [Running Helia in Electron](https://github.com/ipfs-examples/helia-electron) example for how to get started.

**Comment by sosioo** [comment]
OK That's encouraging! Thank you for the link.
