### ISSUE TITLE
re dag-pb-forms-impl-and-use.md#option-2-we-got-the-data-model-form-wrong

### ISSUE THREAD

**Issue by syonfox** [ipfs/helia#192]
https://github.com/ipld/ipld/blob/master/design/tricky-choices/dag-pb-forms-impl-and-use.md#option-2-we-got-the-data-model-form-wrong

```diff
The diff in the IPLD Schema would look something like this:

 type PBNode struct {
-  Links [PBLink]
-  Data optional Bytes
+  data optional Bytes
+  links [PBLink]
 }

 type PBLink struct {
-  Hash Link
+  Cid Link
   Name optional String
-  Tsize optional Int
+  Size optional Int
 }


should be The diff in the IPLD Schema would look something like this:

 type PBNode struct {
  data optional Bytes
  links [PBLink]
 }

 type PBLink struct {
  hash Link
  cid Link
  name optional String
  size optional Int
 }

```

//this matches mdn Set Array etc 

Set.prototype.size - JavaScript - MDN Web Docs - Mozilla
Mozilla Developer
https://developer.mozilla.org › ... › Set
11-Apr-2023 — The value of size is an integer representing how many entries the Set object has. A set accessor function for size is undefined ; you cannot ...
```


How is this handled in helia?

**Comment by achingbrain** [comment]
By design Helia's API is quite limited, it's really just a blockstore and some networking.

It doesn't have an opinion on how the data within the blocks is interpreted, that's left up to wrapping modules such as [@helia/unixfs](https://www.npmjs.com/package/@helia/unixfs).

`kubo` (and by extension `js-ipfs` since it was supposed to mirror the `kubo` API) on the other hand has strong opinions about things like `dag-pb` etc and is hard to change which is why the recommendations in that ipld doc never really saw the light of day (it was written a couple of years ago).

With Helia on the other hand, you'd just implement a new wrapping module that interprets the block data in whatever way today's thinking requires and get on with things.

**Comment by achingbrain** [comment]
Hopefully this answers your question, please do post further discussion topics on https://discuss.ipfs.tech/c/help/helia/40
