### ISSUE TITLE
How to use Orbit DB with Helia?

### ISSUE THREAD

**Issue by GuiFlam** [ipfs/helia#248]
So I have been trying to use OrbitDB, but with ipfs-core, it doesnt seem to work anymore. I have then tried to use it with Helia, but I can't find anything explaining how to do it? 

const ipfs = await IPFS.create() 
const orbitdb = await createOrbitDB({ ipfs})

I am trying to change this to ->

const ipfs= await createHelia()
const orbitdb = await createOrbitDB({ ipfs })

But it doesnt seem to work. I get this error: 'Uncaught (in promise) TypeError: ipfs.id is not a function'

Thanks

**Comment by tymmesyde** [comment]
They are in the process or rewriting it for Helia in this pr for in the nextgen repo: https://github.com/orbitdb/orbit-db-nextgen/pull/62

**Comment by nicocossiom** [comment]
They merged that repo and are working on bringing support for helia at this branch called orbitdb/[helia](https://github.com/orbitdb/orbitdb/tree/helia). There is no ETA afaik, hopefully in the next month or two would be my guess

**Comment by haydenyoung** [comment]
I am one of the contributors on OrbitDB. To update you on the current state of Helia integration; [we have started preliminary development of Helia integration](https://github.com/orbitdb/orbitdb/tree/helia) and are currently working with Protocol Labs on completing a more comprehensive development cycle. We have made numerous attempts at integrating Helia, but because of limited time and with LibP2P currently under heavy development, we have not had immediate success in integrating IPFS's new platform.

In the case of the OP's errors:

- Using Helia WILL NOT WORK. 

- Using with js-ipfs should work. If it isn't, I would recommend posting details of your issue either here or via [OrbitDB's Matrix channel](https://matrix.to/#/#orbitdb_Lobby:gitter.im). I'm going to assume that you are running into [this issue](https://discuss.ipfs.tech/t/importing-js-ipfs-gives-some-webpack-errors-reactjs/13037/6).

OrbitDB is a small project run by volunteers and so there are limitations on time and resources that we, the core contributors, can dedicate to development. We hope to rectify this in the future but at the moment we are fully committed to the development of OrbitDB and are throwing all available time at the project.

**Comment by benzmuircroft** [comment]
@haydenyoung any update?

**Comment by haydenyoung** [comment]
> @haydenyoung any update?

Unfortunately, we were unable to secure formal funding for the Helia integration. Fortunately, we were able to push ahead with a work-in-progress integration and limited testing. Benchmarking and Helia-specific testing along with Helia documentation is currently missing although Helia and Libp2p both provide extensive docs on their respective git repos. There is also example configuration featured in the OrbitDB unit tests. You can [follow the progress here](https://github.com/orbitdb/orbitdb/tree/helia).

**Comment by 2color** [comment]
There's an open PR in the OrbitDB repo: https://github.com/orbitdb/orbitdb/pull/1108.

@haydenyoung we're here if you need any help with the migration to Helia. 

Closing this issue.
