### ISSUE TITLE
Module not found: Error: Package path . is not exported from package

### ISSUE THREAD

**Issue by FabioPinheiro** [ipfs/helia#254]
Probably is a configuration problem in my project
But I get this error:
`Module not found: Error: Package path . is not exported from package <somePath>/node_modules/helia (see exports field in <somePath>/node_modules/helia/package.json)`

Is there a possibility this package is not in the standard format at the browsers expect webpack. (I'm using a relative complex pipeline so I'm unable to easy change it)

**Comment by FabioPinheiro** [comment]
In the package.json I see
```
  "exports": {
    ".": {
      "types": "./dist/src/index.d.ts",
      "import": "./dist/src/index.js"
    }
  }
```

should I did look like this?
```
  "exports": {
    ".": {
      "require": "./dist/src/index.js",
      "types": "./dist/src/index.d.ts",
      "import": "./dist/src/index.js"
    }
  }
```

**Comment by FabioPinheiro** [comment]
Oh I see https://github.com/ipfs/helia/issues/190
Hum seems I'm going to give up on the idea of playing with Helia for now. Since my pipeline is a bit inflexible

**Comment by achingbrain** [comment]
```
"exports": {
    ".": {
      "require": "./dist/src/index.js",
      "types": "./dist/src/index.d.ts",
      "import": "./dist/src/index.js"
    }
  }
```

This will not work because `./dist/src/index.js` is an ESM module and adding `"require"` to the exports map will cause it to be `require`d, and you cannot `require` ESM modules.

You need to configure your project to use ESM, or you need to use [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) but also ensure your project is not transpiling those to `require` behind your back.
