### ISSUE TITLE
helia.blockstore.get hangs when getting non-existent block but blockstore.get (correctly) errors

### ISSUE THREAD

**Issue by haydenyoung** [ipfs/helia#376]
When retrieving a non-existent block by cid using `helia.blockstore.get`, the `get` function hangs indefinitely. However, when accessing `blockstore.get` directly, `get` function immediately throws an error (correct behaviour).

This issue occurs with default MemoryBlockstore only. I'm assuming helia.blockstore is some kind of wrapper around MemoryBlockstore and the error is maybe being caught by the wrapper but the wrapper doesn't exit properly on error?

To replicate:

```
import { createHelia } from 'helia'
import * as Block from 'multiformats/block'
import * as dagCbor from '@ipld/dag-cbor'
import { sha256 } from 'multiformats/hashes/sha2'

const codec = dagCbor
const hasher = sha256


const block = await Block.encode({ value: 'hello world', codec, hasher })
const ipfs = await createHelia()

// await ipfs.blockstore.put(block.cid, 'hello world')

try {
  console.log(await ipfs.blockstore.get(block.cid)) // <-- This never returns, it just hangs indefinitely.
} catch (error) {
  console.log('error') // <-- It never makes it here. But use MemoryBlockstore.get directly and it errors immediately.
} finally {
  await ipfs.stop()
}
```

**Comment by achingbrain** [comment]
Helia wraps the passed blockstore in a network-aware layer - so if you try to get a block without it being present in `node.blockstore`, it'll start searching the network to find it.  By default this means bitswap and HTTP gateways.

The current behaviour of bitswap is to wait until either it finds the block or an abort signal fires* so you should do something like:

```js
try {
  await ipfs.blockstore.get(cid, {
    signal: AbortSignal.timeout(5000) // abort after 5s
  })
} catch (err) {
  //...
}
```

The underlying memory blockstore will throw immediately because it's very simple and doesn't have the network fetch capability.

----

\* = this may change in a future release - the change would be to search for providers, if none are found then give up and throw

**Comment by haydenyoung** [comment]
Thanks @achingbrain makes sense. Your above suggestion worked. Closing.
